set(_CATKIN_CURRENT_PACKAGE "central_server")
set(central_server_VERSION "0.0.0")
set(central_server_MAINTAINER "charisma <charisma@todo.todo>")
set(central_server_PACKAGE_FORMAT "2")
set(central_server_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(central_server_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(central_server_BUILDTOOL_DEPENDS "catkin")
set(central_server_BUILDTOOL_EXPORT_DEPENDS )
set(central_server_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(central_server_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(central_server_TEST_DEPENDS )
set(central_server_DOC_DEPENDS )
set(central_server_URL_WEBSITE "")
set(central_server_URL_BUGTRACKER "")
set(central_server_URL_REPOSITORY "")
set(central_server_DEPRECATED "")